#!/bin/sh
#for VERSION in plone-4.3 plone-4.2 plone-4.1 plone-4.0
for VERSION in plone-4.3
do
echo ================================================================================
    echo Buildout: $VERSION...
    echo ================================================================================
    buildout -c travis-$VERSION.cfg
done
